# OSNet_x0_25_config_final.yaml
model_parameters:
  onnx_model: './osnet_x0_25.onnx'
  march: "bayes-e"
  layer_out_dump: False
  working_dir: 'osnet_64x128_nv12'
  output_model_file_prefix: 'osnet_64x128_nv12'
  debug_mode: "dump_calibration_data"
  remove_node_type: 'Reshape'

input_parameters:
  input_name: "input"
  input_type_rt: 'nv12'          # 运行时输入是NV12
  input_layout_rt: 'NHWC'        # NV12格式必须是NHWC
  input_type_train: 'rgb'        # 训练时输入是RGB
  input_layout_train: 'NCHW'     # 训练时布局
  input_shape: ''                # 从模型读取 [1, 3, 128, 64]
  norm_type: 'data_mean_and_scale'
  mean_value: 123.675 116.28 103.53  # ImageNet标准均值
  scale_value: 0.01712475 0.017507 0.01742919  # ImageNet标准缩放

calibration_parameters:
  cal_data_dir: './reid_image_correct'
  cal_data_type: 'float32'
  calibration_type: 'default'

compiler_parameters:
  compile_mode: 'latency'
  debug: False
  optimize_level: 'O3'
